name: CI/CD Pipeline for Kubernetes Deployment

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to IBM Cloud Container Registry
        run: |
          echo "${{ secrets.zByquoX4pQBaqX_fdtXF2Aybjxpv8A86rpdw4qkE5pbO }}" | ibmcloud login --apikey @-
          ibmcloud cr login

      - name: Build Docker images
        run: |
          docker build -t frontend-app:1.0 ./public
          docker build -t backend-app:1.0 ./server

      - name: Tag Docker images
        run: |
          docker tag frontend-app:1.0 icr.io/my_project123/frontend-app:1.0
          docker tag backend-app:1.0 icr.io/my_project123/backend-app:1.0

      - name: Push Docker images to IBM Cloud Container Registry
        run: |
          docker push icr.io/my_project123/frontend-app:1.0
          docker push icr.io/my_project123/backend-app:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/kubectl

      - name: Deploy applications to Minikube
        run: |
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f backend-deployment.yaml

      - name: Verify deployments
        run: |
          kubectl get pods
          kubectl get svc
